<a href="https://colab.research.google.com/github/cchen744/uhi-extreme-heat-response/blob/landsat/notebooks/01_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**In this notebook, I will quantify Urban Heat Isalnd Effect and Extreme Heat within #CITIES in #CLIMATE_ZONE climate zones.**
<p>
<img src=https://upload.wikimedia.org/wikipedia/commons/7/77/K%C3%B6ppen_Climate_Types_US_50.png align="middle" width=600 />
</p>

Notably, here are following definitions of variables of interest:
- **Urban Heat Island**: Based on land surface temperture, it is defined as SUHI(day) = LST_urb(day) − LST_rur(day), where LST_urb(day) = Aggregate urban pixels (mean or median, predefined) and LST_rur(day) = Aggregate rural reference pixels.
- **Extreme Heat**: Days when the daily mean landsurface temperature overpasses 90 percentile of its historical data.
- **Urban & Rural Definition**：

  - Urban: US Census Urbanized Area
  - Rural: Spatial mean of all non-urban, non-water pixels within the same UA

In [13]:
# Initialize
import os
if not os.path.exists('/content/uhi-extreme-heat-response'):
    !git clone https://github.com/cchen744/uhi-extreme-heat-response.git
%cd /content/uhi-extreme-heat-response
!git fetch origin
!git checkout landsat
!git pull origin landsat
!git config --global user.email cchen744@wisc.edu
!git config --global user.name cchen744

/content/uhi-extreme-heat-response
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 3), reused 5 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (6/6), 2.78 KiB | 2.78 MiB/s, done.
From https://github.com/cchen744/uhi-extreme-heat-response
   6bb430c..9e4cbf5  landsat        -> origin/landsat
   fe91ce4..7aff54a  cell-delta-uhi -> origin/cell-delta-uhi
M	__pycache__/uhi_pipeline.cpython-312.pyc
Already on 'landsat'
Your branch is behind 'origin/landsat' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
From https://github.com/cchen744/uhi-extreme-heat-response
 * branch            landsat    -> FETCH_HEAD
Updating 6bb430c..9e4cbf5
Fast-forward
 uhi_pipeline.py | 103 +++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 1 file changed, 102 insertions(+), 1 deletion(-)

In [14]:
from pathlib import Path
import os
import pandas as pd
import ee
import uhi_pipeline
import importlib
import geemap
importlib.reload(uhi_pipeline)
print("uhi_pipeline module reloaded.")

ee.Authenticate()
ee.Initialize(project='extremeweatheruhi')

DATA_DIR = "/content/drive/MyDrive/UHI/landsat"
# DATA_DIR.mkdir(parents=True, exist_ok=True)

ua_fc = ee.FeatureCollection("projects/extremeweatheruhi/assets/uac20_2025")

uhi_pipeline module reloaded.

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
START_DATE = "2020-06-01"
END_DATE   = "2026-07-29"

In [17]:
intended_cities = ["Madison","Milwaukee",'Seattle','Los Angeles', "Phoenix", 'Nashville','Houston','New York',]
for city_name in intended_cities:
  city = ua_fc.filter(ee.Filter.stringContains("NAME20", city_name))
  city_count = city.size().getInfo()

  if city_count > 0:
        print(f"{city_name} found in ua_fc with {city_count} features.")
        display(geemap.ee_to_df(city))
  else:
      print(f"{city_name} not found in ua_fc.")

Madison found in ua_fc with 7 features.

,ALAND20,AWATER20,FUNCSTAT20,GEOID20,GEOIDFQ20,INTPTLAT20,INTPTLON20,LSAD20,MTFCC20,NAME20,NAMELSAD20,UACE20
0,15523582,0,S,30763,400C200US30763,+40.6289401,-091.3440334,67,G3500,"Fort Madison, IA--IL","Fort Madison, IA--IL Urban Area",30763
1,11145581,0,S,53146,400C200US53146,+44.0079031,-097.1113165,67,G3500,"Madison, SD","Madison, SD Urban Area",53146
2,18568122,0,S,53254,400C200US53254,+35.5160731,-084.3610387,67,G3500,"Madisonville, TN","Madisonville, TN Urban Area",53254
3,12412219,80529,S,53065,400C200US53065,+33.5908189,-083.4689256,67,G3500,"Madison, GA","Madison, GA Urban Area",53065
4,27926905,88900,S,53092,400C200US53092,+38.7741671,-085.3884100,67,G3500,"Madison, IN","Madison, IN Urban Area",53092
5,41735901,306256,S,53227,400C200US53227,+37.3317066,-087.4974109,67,G3500,"Madisonville, KY","Madisonville, KY Urban Area",53227
6,387728991,3305854,S,53200,400C200US53200,+43.0419689,-089.4922081,67,G3500,"Madison, WI","Madison, WI Urban Area",53200

Milwaukee found in ua_fc with 1 features.

,ALAND20,AWATER20,FUNCSTAT20,GEOID20,GEOIDFQ20,INTPTLAT20,INTPTLON20,LSAD20,MTFCC20,NAME20,NAMELSAD20,UACE20
0,1200883174,26161338,S,57466,400C200US57466,+43.0512232,-088.0851008,67,G3500,"Milwaukee, WI","Milwaukee, WI Urban Area",57466

Seattle found in ua_fc with 1 features.

,ALAND20,AWATER20,FUNCSTAT20,GEOID20,GEOIDFQ20,INTPTLAT20,INTPTLON20,LSAD20,MTFCC20,NAME20,NAMELSAD20,UACE20
0,2545796184,149741831,S,80389,400C200US80389,+47.4626540,-122.2745170,67,G3500,"Seattle--Tacoma, WA","Seattle--Tacoma, WA Urban Area",80389

Los Angeles found in ua_fc with 1 features.

,ALAND20,AWATER20,FUNCSTAT20,GEOID20,GEOIDFQ20,INTPTLAT20,INTPTLON20,LSAD20,MTFCC20,NAME20,NAMELSAD20,UACE20
0,4242653496,45567066,S,51445,400C200US51445,+33.9849958,-118.1223950,67,G3500,"Los Angeles--Long Beach--Anaheim, CA","Los Angeles--Long Beach--Anaheim, CA Urban Area",51445

Phoenix found in ua_fc with 2 features.

,ALAND20,AWATER20,FUNCSTAT20,GEOID20,GEOIDFQ20,INTPTLAT20,INTPTLON20,LSAD20,MTFCC20,NAME20,NAMELSAD20,UACE20
0,330537813,985600,S,69192,400C200US69192,+33.4679624,-112.3639331,67,G3500,"Phoenix West--Goodyear--Avondale, AZ","Phoenix West--Goodyear--Avondale, AZ Urban Area",69192
1,2876252398,8810551,S,69184,400C200US69184,+33.4999005,-111.9631531,67,G3500,"Phoenix--Mesa--Scottsdale, AZ","Phoenix--Mesa--Scottsdale, AZ Urban Area",69184

Nashville found in ua_fc with 2 features.

,ALAND20,AWATER20,FUNCSTAT20,GEOID20,GEOIDFQ20,INTPTLAT20,INTPTLON20,LSAD20,MTFCC20,NAME20,NAMELSAD20,UACE20
0,10167128,114650,S,61219,400C200US61219,+31.2060314,-083.2446024,67,G3500,"Nashville, GA","Nashville, GA Urban Area",61219
1,1515057888,13721302,S,61273,400C200US61273,+36.1259094,-086.6911686,67,G3500,"Nashville-Davidson, TN","Nashville-Davidson, TN Urban Area",61273

Houston found in ua_fc with 1 features.

,ALAND20,AWATER20,FUNCSTAT20,GEOID20,GEOIDFQ20,INTPTLAT20,INTPTLON20,LSAD20,MTFCC20,NAME20,NAMELSAD20,UACE20
0,4540250252,65791956,S,40429,400C200US40429,+29.7730212,-095.4003948,67,G3500,"Houston, TX","Houston, TX Urban Area",40429

New York found in ua_fc with 1 features.

WARNING:googleapiclient.http:Sleeping 0.34 seconds before retry 1 of 5 for request: POST https://earthengine.googleapis.com/v1/projects/extremeweatheruhi/table:computeFeatures?alt=json, after 503

,ALAND20,AWATER20,FUNCSTAT20,GEOID20,GEOIDFQ20,INTPTLAT20,INTPTLON20,LSAD20,MTFCC20,NAME20,NAMELSAD20,UACE20
0,8412518721,548326712,S,63217,400C200US63217,+40.7121519,-073.9501839,67,G3500,"New York--Jersey City--Newark, NY--NJ","New York--Jersey City--Newark, NY--NJ Urban Area",63217

In [18]:
CITY_NAME_MAP = {
    'Madison': 'Madison, WI',
    # 'Phoenix': ['Phoenix--Mesa--Scottsdale, AZ', 'Phoenix West--Goodyear--Avondale, AZ'],
    # 'Seattle': 'Seattle--Tacoma, WA',
    # 'Milwaukee': 'Milwaukee, WI',
    # 'New York': 'New York--Jersey City--Newark, NY--NJ',
    # 'Nashville': 'Nashville-Davidson, TN',
    # 'Los Angeles': 'Los Angeles--Long Beach--Anaheim, CA',
    # 'Houston': 'Houston, TX',
}

In [19]:
results = []
for c, full_name in CITY_NAME_MAP.items():
    print(f"=== {c} ===")
    res = uhi_pipeline.build_city_landsat_uhi(
        city_name=full_name,
        ua_fc=ua_fc,
        data_dir=f"{DATA_DIR}/{c.lower()}",
        start_date=START_DATE,
        end_date=END_DATE,
    )
    results.append(res)

pd.DataFrame(results)

=== Madison ===
PRISM p90 threshold = 32.02 degC (summer-only) | extreme days = 61 of 607 summer days
extreme dates: 61 | baseline dates: 546
Madison, WI: saved PRISM labels to /content/drive/MyDrive/UHI/landsat/madison/Madison_WI_prism_labels.csv
Madison, WI: Landsat scenes — extreme = 3, baseline = 30
Madison, WI: export tasks started — check the Tasks tab in the GEE Code Editor or run task.status() to monitor

,city,threshold_C,n_extreme_days,n_baseline_days,n_extreme_scenes,n_baseline_scenes,csv_path,export_tasks
0,"Madison, WI",32.021569,61,546,3,30,/content/drive/MyDrive/UHI/landsat/madison/Mad...,"[BMTLVX7ZLNAJRO2A4OF6CVO3, XZYEC2OJEFAT36QNSEU..."